imports:
    - {resource: '../../../../../../src/Infrastructure/DependencyInjection/Symfony/services.yml'}

services:

  ParkimeterAffiliates\AffiliateBundle\Controller\GetController:
    class: ParkimeterAffiliates\AffiliateBundle\Controller\GetController
    arguments:
      - '@service_container'
      - '@ParkimeterAffiliates\Application\Service\Api\Affiliate\GetAffiliate\GetAffiliateService'
      - '@nil_portugues.serializer.hal_json_serializer'
      - '@ParkimeterAffiliates\Infrastructure\Serializers\JsonVndErrorSerializer'

doctrine:
  orm:
    mappings:
      Affiliate:
        mapping: true
        type: yml
        dir: '%kernel.root_dir%/../../src/Infrastructure/Persistance/Repository/Doctrine/Mapping'
        prefix: 'ParkimeterAffiliates\Domain\Model'
        is_bundle: false

nilportugues_hal_json:
    mappings:
      - "@ParkimeterAffiliatesAffiliateBundle/Resources/serializer"