parkimeter_affiliates_shared:
    resource: "@ParkimeterAffiliatesSharedBundle/Resources/config/routing.yml"

parkimeter_affiliates_affiliate:
    resource: "@ParkimeterAffiliatesAffiliateBundle/Resources/config/routing.yml"

parkimeter_affiliates_click_track:
    resource: "@ParkimeterAffiliatesClickTrackBundle/Resources/config/routing.yml"

parkimeter_affiliates_conversion_track:
    resource: "@ParkimeterAffiliatesConversionTrackBundle/Resources/config/routing.yml"

parkimeter_affiliates_cancellation_track:
    resource: "@ParkimeterAffiliatesCancellationTrackBundle/Resources/config/routing.yml"