imports:
    - {resource: '../../../../../../src/Infrastructure/DependencyInjection/Symfony/services.yml'}

services:

  ParkimeterAffiliates\ClickTrackBundle\Controller\GetController:
    class: ParkimeterAffiliates\ClickTrackBundle\Controller\GetController
    arguments:
      - '@service_container'
      - '@ParkimeterAffiliates\Application\Service\Api\ClickTrack\GetClickTrack\GetClickTrackService'
      - '@nil_portugues.serializer.hal_json_serializer'
      - '@ParkimeterAffiliates\Infrastructure\Serializers\JsonVndErrorSerializer'
