imports:
    - {resource: './affiliate.yml'}
    - {resource: './clickTrack.yml'}
    - {resource: './conversionTrack.yml'}
    - {resource: './cancellationTrack.yml'}

services:
# INFRASTRUCTURE
  ParkimeterAffiliates\Infrastructure\Serializers\JsonVndErrorSerializer:
    class: ParkimeterAffiliates\Infrastructure\Serializers\JsonVndErrorSerializer

  ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\PaginatorOffsetCalculator:
    class: ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\PaginatorOffsetCalculator

  ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\TrackFilterListBuilder:
    class: ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\TrackFilterListBuilder

  ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\TrackFilterQueryBuilder:
    class: ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\TrackFilterQueryBuilder