imports:
    - {resource: './affiliate.yml'}
    - {resource: './clickTrack.yml'}

services:
# INFRASTRUCTURE
  ParkimeterAffiliates\Infrastructure\Serializers\JsonVndErrorSerializer:
    class: ParkimeterAffiliates\Infrastructure\Serializers\JsonVndErrorSerializer

  ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\PaginatorOffsetCalculator:
    class: ParkimeterAffiliates\Infrastructure\Persistance\Repository\Doctrine\Utils\PaginatorOffsetCalculator