click_track_get_many:
    path:     /
    defaults: { _controller: "ParkimeterAffiliatesClickTrackBundle:GetMany:getMany" }
    methods:  GET

click_track_get:
    path:     /{id}
    defaults: { _controller: "ParkimeterAffiliatesClickTrackBundle:Get:get" }
    methods:  GET