services:

  ParkimeterAffiliates\SharedBundle\Command\DumpTracksCommand:
    class: ParkimeterAffiliates\SharedBundle\Command\DumpTracksCommand
    arguments:
      - '@ParkimeterAffiliates\Infrastructure\Persistence\Repository\Doctrine\Affiliate\AffiliateRepository'
      - '@ParkimeterAffiliates\Infrastructure\Persistence\Repository\Doctrine\ClickTrack\ClickTrackRepository'
      - '@ParkimeterAffiliates\Infrastructure\Persistence\Repository\Doctrine\ConversionTrack\ConversionTrackRepository'
      - '@ParkimeterAffiliates\Infrastructure\Persistence\Repository\Doctrine\CancellationTrack\CancellationTrackRepository'
    tags:
      -  { name: console.command }

doctrine:
  orm:
    mappings:
      Affiliate:
        mapping: true
        type: yml
        dir: '%kernel.root_dir%/../../src/Infrastructure/Persistence/Repository/Doctrine/Affiliate/Mapping'
        prefix: 'ParkimeterAffiliates\Domain\Model\Affiliate'
        is_bundle: false
      ClickTrack:
        mapping: true
        type: yml
        dir: '%kernel.root_dir%/../../src/Infrastructure/Persistence/Repository/Doctrine/ClickTrack/Mapping'
        prefix: 'ParkimeterAffiliates\Domain\Model\ClickTrack'
        is_bundle: false
      ConversionTrack:
        mapping: true
        type: yml
        dir: '%kernel.root_dir%/../../src/Infrastructure/Persistence/Repository/Doctrine/ConversionTrack/Mapping'
        prefix: 'ParkimeterAffiliates\Domain\Model\ConversionTrack'
        is_bundle: false
      CancellationTrack:
        mapping: true
        type: yml
        dir: '%kernel.root_dir%/../../src/Infrastructure/Persistence/Repository/Doctrine/CancellationTrack/Mapping'
        prefix: 'ParkimeterAffiliates\Domain\Model\CancellationTrack'
        is_bundle: false

nilportugues_hal_json:
    mappings:
      - "@ParkimeterAffiliatesAffiliateBundle/Resources/serializer"
      - "@ParkimeterAffiliatesClickTrackBundle/Resources/serializer"
      - "@ParkimeterAffiliatesConversionTrackBundle/Resources/serializer"
      - "@ParkimeterAffiliatesCancellationTrackBundle/Resources/serializer"