ParkimeterAffiliates\Domain\Model\CancellationTrack\CancellationTrack:
    type: entity
    table: cancellation_track
    repositoryClass: ParkimeterAffiliates\Infrastructure\Persistence\Repository\Doctrine\CancellationTrack\CancellationTrackRepository
    id:
        id:
            type: integer
            column: cancellation_track_id
            id: true
            generator:
                strategy: AUTO
    fields:
        affiliateId:
            type: integer
        affiliateKey:
            type: string
            length: 64
        cancellationId:
            type: string
            length: 64
        createdAt:
            type: datetime
            column: created_at
        createdAtEpoch:
            type: integer
            column: created_at_epoch
