affiliate_get:
    path:     /{id}
    defaults: { _controller: "ParkimeterAffiliatesAffiliateBundle:Get:get" }
    methods:  GET

affiliate_post:
    path:     /
    defaults: { _controller: "ParkimeterAffiliatesAffiliateBundle:Post:post" }
    methods:  POST
